//! Parity against the **R reference's own outputs**, generated by
//! `generate_goldens.R` from the ClusterX package the R operator runs
//! (JinmiaoChenLab/ClusterX 0.99.1, vendored under `reference/`).
//!
//! Every numeric fixture is written with `%.17g`, so an exact port can be
//! compared exactly (create-rust-operator §6: 15-digit round trips make an
//! exact port look wrong on ties).
//!
//! What each fixture pins:
//!
//! * `lucas_*` — the R operator's own test input (100 observations × 10
//!   variables), `dimReduction = NULL` and `pca` (outDim 2): the gathered
//!   matrix, dc, rho, delta, peakID and the labels, compared exactly (the
//!   pca mapped matrix up to per-column sign).
//! * `lucas_tsne_42_*` — the Rtsne-42 mapping and the labels on it: feeding
//!   the *reference's* mapped matrix through this crate's clustering core
//!   must reproduce the reference's labels exactly.
//! * `lucas_tsne_envelope.csv` — the reference's own label spread across
//!   five seeds; the port's full t-SNE path must land inside it (ARI).
//! * `synthetic12k_*` — 12 000 points, seed 100, which exercises the
//!   `sample(1:n, 10000)` down-sample inside `estimateDc`: the dumped R
//!   sample must be reproduced draw for draw, then dc, rho, delta, peakID
//!   and the labels compared exactly (delta excepted on the
//!   highest-density points, whose value depends on R's random fold
//!   structure — see `algorithm::min_dist_to_higher`).
use clusterx_operator::algorithm::{self, ClusterXResult};
use clusterx_operator::rng::RRng;
use std::collections::HashMap;
use std::io::BufRead;

/// Minimal CSV reader: one header line, comma separated, %.17g numbers.
fn read_csv_rows(path: &str) -> Vec<Vec<String>> {
    let f = std::fs::File::open(path).unwrap_or_else(|e| panic!("read {path}: {e}"));
    let mut lines = std::io::BufReader::new(f).lines();
    let _header = lines.next().unwrap().unwrap();
    lines
        .map(|l| {
            l.unwrap()
                .split(',')
                .map(|s| s.trim().to_string())
                .collect()
        })
        .collect()
}

fn read_column_f64(path: &str, name: &str) -> Vec<f64> {
    let f = std::fs::File::open(path).unwrap_or_else(|e| panic!("read {path}: {e}"));
    let mut lines = std::io::BufReader::new(f).lines();
    let header: Vec<String> = lines
        .next()
        .unwrap()
        .unwrap()
        .split(',')
        .map(|s| s.trim().to_string())
        .collect();
    let i = header
        .iter()
        .position(|h| h == name)
        .unwrap_or_else(|| panic!("{path} has no column {name}"));
    let col = read_csv_rows(path);
    col.iter().map(|r| r[i].parse().unwrap()).collect()
}

fn read_one_f64(path: &str) -> f64 {
    read_column_f64(path, "dc")[0]
}

fn read_lines(path: &str) -> Vec<String> {
    std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("read {path}: {e}"))
        .lines()
        .filter(|l| !l.trim().is_empty())
        .map(|l| l.trim().to_string())
        .collect()
}

fn read_ints(path: &str) -> Vec<usize> {
    read_lines(path)
        .iter()
        .map(|l| l.parse().unwrap())
        .collect()
}

/// The parity directory.
fn dir() -> String {
    concat!(env!("CARGO_MANIFEST_DIR"), "/tests/parity").to_string()
}

/// The gathered matrix, from the R `acast` dump.
fn read_matrix(name: &str) -> Vec<f64> {
    let path = format!("{}/{}", dir(), name);
    let rows = read_csv_rows(&path);
    let n = rows.len();
    let d = rows[0].len();
    let mut data = Vec::with_capacity(n * d);
    for r in &rows {
        for v in r {
            data.push(v.parse().unwrap());
        }
    }
    assert_eq!(data.len(), n * d);
    data
}

/// The lucas input tsv, aggregated exactly as the operator aggregates the
/// crosstab (mean per observation × variable pair), to be checked against
/// the R `acast` dump.
fn gather_lucas() -> (Vec<f64>, usize, usize) {
    let path = format!("{}/lucas_measurement_exp.tsv", dir());
    let lines = read_lines(&path);
    let header: Vec<String> = lines[0]
        .split('\t')
        .map(|s| s.trim_matches('"').to_string())
        .collect();
    let (i_obs, i_var, i_val) = (
        header.iter().position(|h| h == "Observation").unwrap(),
        header.iter().position(|h| h == "Variable").unwrap(),
        header.iter().position(|h| h == "Measurement").unwrap(),
    );
    let mut sums: HashMap<(String, String), (f64, u32)> = HashMap::new();
    for l in &lines[1..] {
        let f: Vec<String> = l
            .split('\t')
            .map(|s| s.trim_matches('"').to_string())
            .collect();
        let e = sums
            .entry((f[i_obs].clone(), f[i_var].clone()))
            .or_insert((0.0, 0));
        e.0 += f[i_val].parse::<f64>().unwrap();
        e.1 += 1;
    }
    let mut obs: Vec<String> = sums.keys().map(|k| k.0.clone()).collect();
    obs.sort();
    obs.dedup();
    let mut vars: Vec<String> = sums.keys().map(|k| k.1.clone()).collect();
    vars.sort();
    vars.dedup();
    let (n, d) = (obs.len(), vars.len());
    let mut data = vec![0.0; n * d];
    for ((o, v), (sum, count)) in &sums {
        let i = obs.iter().position(|x| x == o).unwrap();
        let k = vars.iter().position(|x| x == v).unwrap();
        data[i * d + k] = sum / *count as f64;
    }
    (data, n, d)
}

fn clusterx_null(data: &[f64], n: usize, d: usize, seed: u32) -> ClusterXResult {
    let mut rng = RRng::set_seed(seed);
    algorithm::clusterx(data, n, d, 0.001, &mut rng).expect("clusterx")
}

/// The golden cluster files carry R's raw cluster vector (ints, `NA` where
/// the reference leaves NA); the operator's output renders them
/// `paste0("cluster", cluster)` — see `output::label`.
fn raw_labels(res: &ClusterXResult) -> Vec<String> {
    res.cluster
        .iter()
        .map(|c| match c {
            Some(k) => k.to_string(),
            None => "NA".to_string(),
        })
        .collect()
}

/// Compare `delta` allowing the maximum-density point(s) to differ: their
/// value in R depends on the random fold structure of its chunk (see
/// `algorithm::min_dist_to_higher`).
fn assert_delta_close(res: &ClusterXResult, want: &[f64], what: &str) {
    let rho_max = res.rho.iter().copied().fold(f64::NEG_INFINITY, f64::max);
    let mut worst = 0.0f64;
    for (i, (&got, &w)) in res.delta.iter().zip(want).enumerate() {
        if res.rho[i] >= rho_max {
            continue; // the fold-dependent value
        }
        let rel = (got - w).abs() / w.abs().max(1e-12);
        worst = worst.max(rel);
    }
    assert!(
        worst <= 1e-12,
        "{what}: delta differs from the reference by {worst:e}"
    );
}

#[test]
fn gathering_reproduces_the_r_acast_matrix_bitwise() {
    let (data, n, d) = gather_lucas();
    let want = read_matrix("lucas_matrix.csv");
    assert_eq!((n, d), (100, 10));
    let worst = data
        .iter()
        .zip(&want)
        .map(|(a, b)| (a - b).abs() / b.abs().max(1e-12))
        .fold(0.0f64, f64::max);
    assert!(worst == 0.0, "gathered matrix differs by {worst:e}");
}

#[test]
fn lucas_null_reproduces_the_reference_exactly() {
    let (data, n, d) = gather_lucas();
    let res = clusterx_null(&data, n, d, 42);

    assert_eq!(
        res.dc,
        read_one_f64(&format!("{}/lucas_null_dc.csv", dir()))
    );
    let rho = read_column_f64(&format!("{}/lucas_null_rho_delta.csv", dir()), "rho");
    let delta = read_column_f64(&format!("{}/lucas_null_rho_delta.csv", dir()), "delta");
    // rho is a 100-term sum; R accumulates in long double, this port in f64,
    // so agreement is at the 1e-14 level, not bitwise.
    for (i, (&a, &b)) in res.rho.iter().zip(&rho).enumerate() {
        let rel = (a - b).abs() / b.abs().max(1e-12);
        assert!(rel <= 1e-12, "rho[{i}]: {a} vs {b} ({rel:e})");
    }
    assert_delta_close(&res, &delta, "lucas null");
    assert_eq!(
        res.peak_id.iter().map(|p| p + 1).collect::<Vec<_>>(),
        read_ints(&format!("{}/lucas_null_peakID.csv", dir()))
    );
    assert_eq!(
        raw_labels(&res),
        read_lines(&format!("{}/lucas_null_cluster.csv", dir()))
    );
}

#[test]
fn lucas_pca_reproduces_the_reference_up_to_sign() {
    let (data, n, d) = gather_lucas();
    let out_dim = 2;
    let mapped = clusterx_operator::dimred::pca_scaled(&data, n, d, out_dim).unwrap();
    let want = read_matrix("lucas_pca_mapped.csv");
    // per-column: equal to the reference up to a global sign
    for k in 0..out_dim {
        let mut sum = 0.0;
        for i in 0..n {
            let a = mapped[i * out_dim + k];
            let b = want[i * out_dim + k];
            let s = a * b;
            sum += s.abs() - s; // 0 when both have the same sign
            let tol = 1e-9 * b.abs().max(1e-12) + 1e-12;
            assert!(
                (a.abs() - b.abs()).abs() <= tol,
                "pca axis {k} row {i}: |{a}| vs |{b}|"
            );
        }
        assert!(
            sum == 0.0 || sum / (n as f64) < 1e-9,
            "pca axis {k} mixes signs against the reference"
        );
    }
    let res = {
        let mut rng = RRng::set_seed(42);
        algorithm::clusterx(&mapped, n, out_dim, 0.001, &mut rng).unwrap()
    };
    // A reflection is an isometry, but the port's PCA values differ from
    // LAPACK's in the last bits, and the dc search's binary steps can land
    // one iteration apart on a 1e-15 perturbation — so dc agrees to ~1e-14,
    // not bitwise.
    let want_dc = read_one_f64(&format!("{}/lucas_pca_dc.csv", dir()));
    assert!(
        (res.dc - want_dc).abs() / want_dc < 1e-12,
        "pca dc: {} vs {want_dc}",
        res.dc
    );
    let rho = read_column_f64(&format!("{}/lucas_pca_rho_delta.csv", dir()), "rho");
    for (i, (&a, &b)) in res.rho.iter().zip(&rho).enumerate() {
        // isolated points have rho near zero, where a relative tolerance is
        // meaningless; the mapped values themselves agree to ~1e-12 absolute
        assert!(
            (a - b).abs() <= 1e-9 * b.abs() + 1e-9,
            "pca rho[{i}]: {a} vs {b}"
        );
    }
    assert_eq!(
        raw_labels(&res),
        read_lines(&format!("{}/lucas_pca_cluster.csv", dir()))
    );
}

#[test]
fn the_clustering_core_reproduces_the_reference_on_the_reference_tsne_map() {
    // The exact test of the core on t-SNE-shaped data: take the mapping the
    // reference produced with seed 42, cluster it here, and require the same
    // dc, rho, delta, peakID and labels.
    let want = read_matrix("lucas_tsne_42_mapped.csv");
    let n = want.len() / 2;
    let res = clusterx_null(&want, n, 2, 42);

    assert_eq!(
        res.dc,
        read_one_f64(&format!("{}/lucas_tsne42map_dc.csv", dir())),
        "dc on the reference's tsne mapping must match bitwise"
    );
    let raw: Vec<Vec<String>> =
        std::fs::read_to_string(format!("{}/lucas_tsne42map_rho_delta.csv", dir()))
            .unwrap()
            .lines()
            .skip(1) // header: rho,delta,higherID
            .map(|l| l.split(',').map(|x| x.trim().to_string()).collect())
            .collect();
    let want_rho: Vec<f64> = raw.iter().map(|r| r[0].parse().unwrap()).collect();
    for (i, (&a, &b)) in res.rho.iter().zip(&want_rho).enumerate() {
        let rel = (a - b).abs() / b.abs().max(1e-12);
        assert!(rel <= 1e-12, "tsne-map rho[{i}]: {a} vs {b} ({rel:e})");
    }
    let want_delta: Vec<f64> = raw.iter().map(|r| r[1].parse().unwrap()).collect();
    assert_delta_close(&res, &want_delta, "tsne map");
    let want_higher: Vec<usize> = raw.iter().map(|r| r[2].parse().unwrap()).collect();
    for (i, (&a, &b)) in res.higher_id.iter().zip(&want_higher).enumerate() {
        assert_eq!(a + 1, b, "tsne-map higherID[{i}] differs");
    }
    assert_eq!(
        res.peak_id.iter().map(|p| p + 1).collect::<Vec<_>>(),
        read_ints(&format!("{}/lucas_tsne42map_peakID.csv", dir()))
    );
    // this golden carries the operator's rendered labels (paste0("cluster", k))
    let rendered: Vec<String> = res
        .cluster
        .iter()
        .map(|c| match c {
            Some(k) => format!("cluster{k}"),
            None => "clusterNA".to_string(),
        })
        .collect();
    assert_eq!(
        rendered,
        read_lines(&format!("{}/lucas_tsne_42_cluster.csv", dir()))
    );
}

#[test]
fn the_full_tsne_path_lands_inside_the_reference_reseed_envelope() {
    let (data, n, d) = gather_lucas();
    let mut rng = RRng::set_seed(42);
    let mapped = clusterx_operator::dimred::tsne(&data, n, d, &mut rng).unwrap();
    let res = clusterx_null(&mapped, n, 2, 42);
    let rust_labels: Vec<String> = res
        .cluster
        .iter()
        .map(|c| match c {
            Some(k) => format!("cluster{k}"),
            None => "clusterNA".to_string(),
        })
        .collect();

    // The envelope: pairwise ARIs between the reference's own five seeds,
    // with a floor above a random partition (~0) so the test can fail —
    // the reference's own spread dips slightly below zero, which would make
    // any labelling pass (revglm review, 2026-09-23).
    let env = read_csv_rows(&format!("{}/lucas_tsne_envelope.csv", dir()));
    let mut min_ari = f64::INFINITY;
    let mut seeds: Vec<(usize, usize, f64)> = Vec::new();
    for r in &env {
        let a: usize = r[0].parse().unwrap();
        let b: usize = r[1].parse().unwrap();
        let ari: f64 = r[2].parse().unwrap();
        min_ari = min_ari.min(ari);
        seeds.push((a, b, ari));
    }
    let floor = min_ari.max(0.10);
    // The reference's labels at each seed, re-derived from the envelope?
    // No — the reference's seed-42 labels are committed; compare against
    // them with the spread's floor as the bar.
    let want = read_lines(&format!("{}/lucas_tsne_42_cluster.csv", dir()));
    let got_ari = ari(&rust_labels, &want);
    assert!(
        got_ari >= floor,
        "ARI(port, reference @ seed 42) = {got_ari:.4} is below the floor {floor:.4} \
         (reference's own spread floor {min_ari:.4})"
    );
    println!(
        "tsne reseed envelope: floor {floor:.4} (spread floor {min_ari:.4}), \
         port vs reference {got_ari:.4} ({} pairwise ARIs)",
        seeds.len()
    );
}

/// Adjusted Rand index, matching the base-R definition in the generator.
fn ari(a: &[String], b: &[String]) -> f64 {
    let mut classes: HashMap<(&str, &str), usize> = HashMap::new();
    let mut ca: HashMap<&str, usize> = HashMap::new();
    let mut cb: HashMap<&str, usize> = HashMap::new();
    for (x, y) in a.iter().zip(b) {
        *classes.entry((x.as_str(), y.as_str())).or_insert(0) += 1;
        *ca.entry(x.as_str()).or_insert(0) += 1;
        *cb.entry(y.as_str()).or_insert(0) += 1;
    }
    let choose2 = |x: usize| x as f64 * (x as f64 - 1.0) / 2.0;
    let sum_ij: f64 = classes.values().map(|&c| choose2(c)).sum();
    let sum_a: f64 = ca.values().map(|&c| choose2(c)).sum();
    let sum_b: f64 = cb.values().map(|&c| choose2(c)).sum();
    let n = choose2(a.len());
    let expected = sum_a * sum_b / n;
    let max_index = (sum_a + sum_b) / 2.0;
    (sum_ij - expected) / (max_index - expected)
}

#[test]
fn the_rng_reproduces_rs_sample_of_the_12000_point_fixture() {
    // estimateDc down-samples with sample(1:n, 10000, replace = FALSE) once
    // the projection has more than 10 000 points. The dumped sample is what
    // R 4.3 drew with set.seed(100).
    let want: Vec<usize> = read_ints(&format!("{}/synthetic12k_sample.csv", dir()));
    assert_eq!(want.len(), 10_000);
    let mut rng = RRng::set_seed(100);
    let got = rng.sample_int(12000, 10_000);
    assert_eq!(got, want.iter().map(|x| x - 1).collect::<Vec<_>>());
}

#[test]
fn synthetic12k_exercises_the_downsample_path_exactly() {
    let data = read_matrix("synthetic12k_matrix.csv");
    let n = data.len() / 8;
    assert_eq!(n, 12000);
    let d = 8;
    let res = clusterx_null(&data, n, d, 100);

    assert_eq!(
        res.dc,
        read_one_f64(&format!("{}/synthetic12k_dc.csv", dir())),
        "dc, sampled with R's own algorithm, must match bitwise"
    );
    let rho = read_column_f64(&format!("{}/synthetic12k_rho_delta.csv", dir()), "rho");
    for (i, (&a, &b)) in res.rho.iter().zip(&rho).enumerate() {
        let rel = (a - b).abs() / b.abs().max(1e-12);
        assert!(rel <= 1e-12, "rho[{i}]: {a} vs {b} ({rel:e})");
    }
    let delta = read_column_f64(&format!("{}/synthetic12k_rho_delta.csv", dir()), "delta");
    assert_delta_close(&res, &delta, "synthetic12k");
    assert_eq!(
        res.peak_id.iter().map(|p| p + 1).collect::<Vec<_>>(),
        read_ints(&format!("{}/synthetic12k_peakID.csv", dir()))
    );
    assert_eq!(
        raw_labels(&res),
        read_lines(&format!("{}/synthetic12k_cluster.csv", dir()))
    );
}

#[test]
fn the_dc_search_refuses_shapes_the_reference_loops_forever_on() {
    // n = 2: the neighbour rate can only be 0 or 0.5, never inside
    // (0.01, 0.02); R's while(TRUE) never returns. The port bails out.
    let data = vec![1.0, 2.0, 3.0, 4.0];
    let mut rng = RRng::set_seed(1);
    let e = algorithm::clusterx(&data, 2, 2, 0.001, &mut rng).unwrap_err();
    assert!(
        e.to_string().contains("at least 2 are needed")
            || e.to_string().contains("did not converge"),
        "unexpected error: {e}"
    );
}

/// `operator.json`'s spec is hand-written, so compare it with what the code
/// actually reads and produces. Five of eight properties went undeclared in
/// the asinh operator and nobody could have set them.
#[test]
fn operator_spec_matches_the_code() {
    let manifest = concat!(env!("CARGO_MANIFEST_DIR"), "/operator.json");
    let spec: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(manifest).unwrap()).unwrap();

    let declared: Vec<&str> = spec["properties"]
        .as_array()
        .unwrap()
        .iter()
        .map(|p| p["name"].as_str().unwrap())
        .collect();
    for name in ["dimReduction", "outDim", "seed"] {
        assert!(
            declared.contains(&name),
            "property '{name}' is read by the operator but not declared in operator.json"
        );
    }
    let values: Vec<&str> = spec["properties"]
        .as_array()
        .unwrap()
        .iter()
        .find(|p| p["name"] == "dimReduction")
        .unwrap()["values"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_str().unwrap())
        .collect();
    assert_eq!(values, ["tsne", "pca", "NULL"]);

    let default_of = |name: &str| -> serde_json::Value {
        spec["properties"]
            .as_array()
            .unwrap()
            .iter()
            .find(|p| p["name"] == name)
            .unwrap()["defaultValue"]
            .clone()
    };
    let d = clusterx_operator::props::Settings::default();
    assert_eq!(default_of("outDim").as_f64().unwrap(), d.out_dim as f64);
    assert_eq!(default_of("seed").as_f64().unwrap(), d.seed as f64);
    assert_eq!(
        default_of("dimReduction").as_str().unwrap(),
        "NULL",
        "the manifest's default dimReduction must match Settings::default()"
    );

    // the result columns: a per-column result joined on .ci, one attribute
    let join = &spec["operatorSpec"]["outputSpecsV2"][0]["joinOperators"][0];
    assert_eq!(
        join["leftPair"]["lColumns"],
        serde_json::json!(["Observation"])
    );
    assert_eq!(join["rightRelation"]["attributes"][0]["name"], "cluster");
    assert_eq!(join["rightRelation"]["attributes"][0]["type"], "string");
    assert_eq!(
        clusterx_operator::output::cluster_column("ds0"),
        "ds0.cluster",
        "the written column and the declared attribute have drifted apart"
    );
}
